version: '3'

services:
  backend:
    image: local-backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: "postgres:10-alpine"
    ports:
      - "5433:5432"
    volumes:
      - toplist_volume:/var/lib/postgresql/data

volumes:
  toplist_volume:
