version: '3'

services:
  backend:
    image: local-backend_minio:latest
    ports:
      - "8000:8000"
    env_file:
      - docker.env
    depends_on:
      - postgres
      - storage

  postgres:
    image: "postgres:10-alpine"
    ports:
      - "5432:5432"
    volumes:
      - toplist_volume:/var/lib/postgresql/data

  storage:
    image: minio/minio:latest
    command: 'server /data'
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: KBP6WXGPS387090EZMG8
      MINIO_SECRET_KEY: DRjFXylyfMqn2zilAr33xORhaYz5r9e8r37XPz3A
    volumes:
      - minio_toplist_volume:/data

volumes:
  toplist_volume:
  minio_toplist_volume:
