# Generated by Django 2.2.3 on 2019-08-27 08:42

from django.db import migrations, models
import django_enum_choices.choice_builders
import django_enum_choices.fields
import recommendation_list.models.recommendations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=1000)),
                ('photo', models.ImageField(null=True, upload_to='recommendation_images')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_draft', models.BooleanField(default=False)),
                ('photo', models.ImageField(null=True, upload_to='recommendation_list_images')),
                ('category', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('movies', 'movies'), ('books', 'books'), ('relax', 'relax'), ('knowledge', 'knowledge'), ('music', 'music'), ('games', 'games'), ('free theme', 'free theme')], enum_class=recommendation_list.models.recommendations.CategoryEnum, max_length=10)),
                ('header', models.CharField(default='', max_length=500)),
                ('description', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
