# Generated by Django 2.2.3 on 2019-08-27 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('recommendation_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationlist',
            name='likes',
            field=models.ManyToManyField(related_name='likes', through='recommendation_list.Likes', to='user.CustomUser'),
        ),
        migrations.AddField(
            model_name='recommendationlist',
            name='tags',
            field=models.ManyToManyField(to='recommendation_list.Tag'),
        ),
        migrations.AddField(
            model_name='recommendationlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='user.CustomUser'),
        ),
        migrations.AddField(
            model_name='recommendationlist',
            name='users',
            field=models.ManyToManyField(related_name='favorites', through='recommendation_list.Favorites', to='user.CustomUser'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommendation_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendation_list.RecommendationList'),
        ),
        migrations.AddField(
            model_name='likes',
            name='recommendation_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_recommendations', to='recommendation_list.RecommendationList'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_user', to='user.CustomUser'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='recommendation_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_recommendations', to='recommendation_list.RecommendationList'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_user', to='user.CustomUser'),
        ),
    ]
